#!/usr/bin/env node
// build.mjs — プラグインの完全ビルド
//
//   1. manifest.json の build 番号を +1 (kintone 側の単調増加要件)
//   2. src/desktop/index.tsx → plugin/js/desktop.js (esbuild / IIFE)
//   3. src/config/index.tsx  → plugin/js/config.js  (esbuild / IIFE)
//   4. src/styles/global.css + Tailwind → plugin/css/desktop.css
//   5. plugin/css/config.css は簡易 (グローバルスタイル共通)
//
// 出力先 plugin/js/* と plugin/css/desktop.css は .gitignore で除外 (生成物)

import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import * as esbuild from 'esbuild';

const MANIFEST_PATH = resolve('plugin/manifest.json');
const JS_OUT_DIR = resolve('plugin/js');
const CSS_OUT_DIR = resolve('plugin/css');

// ----- 1. manifest.json の build 番号を +1 ---------------------------------
function bumpBuildNumber() {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));
  const old = Number(manifest.version);
  if (!Number.isInteger(old) || old < 1) {
    throw new Error(`manifest.json の version が整数ではありません: ${manifest.version}`);
  }
  manifest.version = old + 1;
  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`[build] manifest.json version (build): ${old} → ${manifest.version}`);
  return manifest.version;
}

// ----- 2pre. Worker (kintone-mcp) を ES module バンドル → 文字列で注入 ------
// Plugin Config の Cloudflare デプロイ機能で使う。Plugin が JS 文字列として保持し
// Cloudflare Workers API へ PUT で送信する。
// バージョン情報は esbuild --define で注入し、Worker /version で確認可能にする。
async function bundleWorkerAsString(buildVersion, buildTime) {
  const WORKER_ENTRY = resolve('../kintone-mcp/src/index.ts');
  const result = await esbuild.build({
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    loader: { '.ts': 'ts' },
    minify: true,
    sourcemap: false,
    write: false,
    logLevel: 'warning',
    entryPoints: [WORKER_ENTRY],
    define: {
      __BUILD_VERSION__: JSON.stringify(buildVersion),
      __BUILD_TIME__: JSON.stringify(buildTime),
    },
  });
  const text = result.outputFiles[0]?.text ?? '';
  if (!text) throw new Error('worker bundle is empty');
  const outPath = resolve('src/generated/worker-bundle.ts');
  mkdirSync(resolve('src/generated'), { recursive: true });
  const escaped = text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const ts = `// AUTO-GENERATED by scripts/build.mjs — DO NOT EDIT
// kintone-mcp Worker bundle (ES module). Plugin Config の Cloudflare デプロイで送信される。

export const WORKER_BUNDLE_JS = \`${escaped}\`;
export const WORKER_BUNDLE_BYTES = ${text.length};
export const WORKER_BUNDLE_VERSION = ${JSON.stringify(buildVersion)};
export const WORKER_BUNDLE_BUILT_AT = ${JSON.stringify(buildTime)};
`;
  writeFileSync(outPath, ts);
  console.log(`[build] src/generated/worker-bundle.ts generated (${text.length} bytes, version=${buildVersion})`);
}

// ----- 2-3. esbuild で 2 エントリを IIFE バンドル (並行) --------------------
async function bundleJs(pluginBuild, semver) {
  mkdirSync(JS_OUT_DIR, { recursive: true });

  const commonOptions = {
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    jsx: 'automatic',
    loader: { '.ts': 'ts', '.tsx': 'tsx' },
    minify: true,
    sourcemap: false,
    logLevel: 'warning',
    // VersionBadge / config 画面で表示用に
    //   __PLUGIN_VERSION__: build 番号 (manifest.json の整数)
    //   __PLUGIN_SEMVER__: semver (package.json の version)
    define: {
      __PLUGIN_VERSION__: JSON.stringify(String(pluginBuild)),
      __PLUGIN_SEMVER__: JSON.stringify(semver),
    },
  };

  await Promise.all([
    esbuild.build({
      ...commonOptions,
      entryPoints: ['src/desktop/index.tsx'],
      outfile: resolve(JS_OUT_DIR, 'desktop.js'),
    }),
    esbuild.build({
      ...commonOptions,
      entryPoints: ['src/config/index.tsx'],
      outfile: resolve(JS_OUT_DIR, 'config.js'),
    }),
  ]);
  console.log('[build] plugin/js/{desktop,config}.js generated');
}

// ----- 4-5. Tailwind CSS ビルド --------------------------------------------
function buildCss() {
  mkdirSync(CSS_OUT_DIR, { recursive: true });

  // desktop 用 CSS (グローバル + Tailwind)
  const desktopOut = resolve(CSS_OUT_DIR, 'desktop.css');
  const result = spawnSync(
    'tailwindcss',
    [
      '-i',
      'src/styles/global.css',
      '-o',
      desktopOut,
      '--minify',
    ],
    { stdio: 'inherit' },
  );
  if (result.status !== 0) {
    throw new Error(`tailwindcss build failed with exit ${result.status}`);
  }
  console.log('[build] plugin/css/desktop.css generated');

  // config 画面も同じスタイルを使う (小さいのでコピー)
  const contents = readFileSync(desktopOut, 'utf-8');
  writeFileSync(resolve(CSS_OUT_DIR, 'config.css'), contents);
  console.log('[build] plugin/css/config.css generated');
}

// ----- main ----------------------------------------------------------------
async function main() {
  const pluginBuild = bumpBuildNumber();
  const semver = (() => {
    try {
      const pkg = JSON.parse(readFileSync(resolve('package.json'), 'utf-8'));
      return typeof pkg.version === 'string' ? pkg.version : '0.0.0';
    } catch {
      return '0.0.0';
    }
  })();
  // Worker のバージョンは Plugin の build 番号 + ビルド時刻 (ISO8601 秒精度)
  const buildTime = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  const buildVersion = `plugin.${pluginBuild}+${buildTime}`;

  // Worker バンドル → Plugin JS の順序依存はない (Worker の出力は Plugin の generated/ に
  // 書き出され、Plugin の bundleJs はそれを読みに行く) — ので bundleWorkerAsString が
  // 先に終わっていればよい。CSS は完全独立。
  await bundleWorkerAsString(buildVersion, buildTime);
  await Promise.all([bundleJs(pluginBuild, semver), Promise.resolve(buildCss())]);
  console.log(`[build] done (semver=${semver}, build=${pluginBuild})`);
}

main().catch((err) => {
  console.error('[build] failed:', err);
  process.exit(1);
});
