#!/usr/bin/env node
// build.mjs — プラグインの完全ビルド
//
//   1. manifest.json の build 番号を +1 (kintone 側の単調増加要件)
//   2. src/desktop/index.tsx → plugin/js/desktop.js (esbuild / IIFE)
//   3. src/config/index.tsx  → plugin/js/config.js  (esbuild / IIFE)
//   4. src/styles/global.css + Tailwind → plugin/css/desktop.css
//   5. plugin/css/config.css は簡易 (グローバルスタイル共通)
//
// 出力先 plugin/js/* と plugin/css/desktop.css は .gitignore で除外 (生成物)

import { spawnSync } from 'node:child_process';
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';

import * as esbuild from 'esbuild';

const MANIFEST_PATH = resolve('plugin/manifest.json');
const JS_OUT_DIR = resolve('plugin/js');
const CSS_OUT_DIR = resolve('plugin/css');

// ----- 1. manifest.json の build 番号を +1 ---------------------------------
/**
 * docs/design-handoff/customizer-wedge/tokens.json → src/styles/tokens.css を再生成。
 * 詳細は scripts/build-tokens.mjs を参照。
 */
function buildTokens() {
  const result = spawnSync(process.execPath, [resolve('scripts/build-tokens.mjs')], {
    stdio: 'inherit',
  });
  if (result.status !== 0) {
    throw new Error('build-tokens.mjs が失敗しました');
  }
}

function bumpBuildNumber() {
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf-8'));
  const old = Number(manifest.version);
  if (!Number.isInteger(old) || old < 1) {
    throw new Error(`manifest.json の version が整数ではありません: ${manifest.version}`);
  }
  manifest.version = old + 1;
  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
  console.log(`[build] manifest.json version (build): ${old} → ${manifest.version}`);
  return manifest.version;
}

// ----- 2pre. Worker (kintone-mcp) を ES module バンドル → 文字列で注入 ------
// Plugin Config の Cloudflare デプロイ機能で使う。Plugin が JS 文字列として保持し
// Cloudflare Workers API へ PUT で送信する。
// バージョン情報は esbuild --define で注入し、Worker /version で確認可能にする。
async function bundleWorkerAsString(buildVersion, buildTime) {
  const WORKER_ENTRY = resolve('../kintone-mcp/src/index.ts');
  const result = await esbuild.build({
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    loader: { '.ts': 'ts' },
    minify: true,
    sourcemap: false,
    write: false,
    logLevel: 'warning',
    entryPoints: [WORKER_ENTRY],
    define: {
      __BUILD_VERSION__: JSON.stringify(buildVersion),
      __BUILD_TIME__: JSON.stringify(buildTime),
    },
  });
  const text = result.outputFiles[0]?.text ?? '';
  if (!text) throw new Error('worker bundle is empty');
  const outPath = resolve('src/generated/worker-bundle.ts');
  mkdirSync(resolve('src/generated'), { recursive: true });
  const escaped = text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const ts = `// AUTO-GENERATED by scripts/build.mjs — DO NOT EDIT
// kintone-mcp Worker bundle (ES module). Plugin Config の Cloudflare デプロイで送信される。

export const WORKER_BUNDLE_JS = \`${escaped}\`;
export const WORKER_BUNDLE_BYTES = ${text.length};
export const WORKER_BUNDLE_VERSION = ${JSON.stringify(buildVersion)};
export const WORKER_BUNDLE_BUILT_AT = ${JSON.stringify(buildTime)};
`;
  writeFileSync(outPath, ts);
  console.log(`[build] src/generated/worker-bundle.ts generated (${text.length} bytes, version=${buildVersion})`);
}

// ----- 2pre-2. Skill bundle 生成 (packages/plugin/src/skills/*/SKILL.md) ---
// Issue #30: 各 skill ディレクトリの SKILL.md を読み取り、YAML frontmatter から
// name / description を抽出 → ConfigScreen 「Skills 同期」ボタンが Worker
// /skills/sync 経由で Anthropic にアップロードできる形に焼き込む。
// 全体の SHA-256 ハッシュも記録し、内容変更を resolveAgent.ts metadata
// (skillsVersion) に反映できるようにする。
const SKILLS_DIR = resolve('src/skills');
const SKILL_RESERVED_NAMES = new Set(['anthropic', 'claude']);

function parseSkillMd(filePath) {
  const text = readFileSync(filePath, 'utf-8');
  const m = text.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);
  if (!m) throw new Error(`SKILL.md frontmatter missing: ${filePath}`);
  const fm = m[1];
  const body = m[2];
  const name = (fm.match(/^name:\s*(.+)$/m) ?? [])[1]?.trim();
  // description は複数行に渡る可能性あり (>- や YAML 多行)。シンプルに 1 行で受ける
  const description = (fm.match(/^description:\s*(.+)$/m) ?? [])[1]?.trim();
  if (!name) throw new Error(`SKILL.md frontmatter missing 'name': ${filePath}`);
  if (!description) throw new Error(`SKILL.md frontmatter missing 'description': ${filePath}`);
  if (!/^[a-z][a-z0-9-]{0,63}$/.test(name)) {
    throw new Error(`SKILL.md 'name' must match /^[a-z][a-z0-9-]{0,63}$/: ${name}`);
  }
  if (SKILL_RESERVED_NAMES.has(name)) {
    throw new Error(`SKILL.md 'name' uses reserved word: ${name}`);
  }
  if (description.length > 1024) {
    throw new Error(`SKILL.md 'description' exceeds 1024 chars: ${filePath}`);
  }
  return { name, description, skillMd: text, body };
}

function collectSkills() {
  let entries = [];
  try {
    entries = readdirSync(SKILLS_DIR);
  } catch {
    return [];
  }
  const skills = [];
  for (const entry of entries.sort()) {
    const dir = resolve(SKILLS_DIR, entry);
    let st;
    try { st = statSync(dir); } catch { continue; }
    if (!st.isDirectory()) continue;
    const md = resolve(dir, 'SKILL.md');
    try { statSync(md); } catch { continue; } // SKILL.md が無いディレクトリは無視
    const parsed = parseSkillMd(md);
    if (parsed.name !== entry) {
      throw new Error(`Skill directory '${entry}' does not match frontmatter name '${parsed.name}'`);
    }
    skills.push({
      name: parsed.name,
      displayTitle: parsed.name, // 現状 display_title = name で十分
      description: parsed.description,
      skillMd: parsed.skillMd,
    });
  }
  return skills;
}

function generateSkillsBundle() {
  const skills = collectSkills();
  const hash = createHash('sha256');
  for (const s of skills) {
    hash.update(s.name + '\0' + s.skillMd);
  }
  const skillsVersion = `sha256:${hash.digest('hex').slice(0, 16)}`;
  const outPath = resolve('src/generated/skills-bundle.ts');
  mkdirSync(resolve('src/generated'), { recursive: true });
  const skillsJson = JSON.stringify(skills, null, 2);
  const ts = `// AUTO-GENERATED by scripts/build.mjs — DO NOT EDIT
// kintone 固有 custom skills (packages/plugin/src/skills/*/SKILL.md) の bundle。
// ConfigScreen 「Skills 同期」ボタンが Worker /skills/sync 経由で Anthropic に
// upload する。resolveAgent.ts は SKILLS_VERSION を metadata.skillsVersion に
// 含めて、skill 内容変化で別 Agent 扱いにする。

export interface SkillBundle {
  /** Anthropic SKILL.md 内 \`name\` (lowercase + hyphen) */
  name: string;
  /** display_title フィールドに使う表示用ラベル (現状 name と同じ) */
  displayTitle: string;
  /** description (context 常駐用、Agent が呼出可否判断に使う) */
  description: string;
  /** SKILL.md の全文 (frontmatter + 本文) */
  skillMd: string;
}

export const SKILL_BUNDLES: SkillBundle[] = ${skillsJson};

export const SKILLS_VERSION = ${JSON.stringify(skillsVersion)};
`;
  writeFileSync(outPath, ts);
  console.log(`[build] src/generated/skills-bundle.ts generated (${skills.length} skills, version=${skillsVersion})`);
}

// ----- 2-3. esbuild で 2 エントリを IIFE バンドル (並行) --------------------
async function bundleJs(pluginBuild, semver) {
  mkdirSync(JS_OUT_DIR, { recursive: true });

  const commonOptions = {
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2020',
    jsx: 'automatic',
    loader: { '.ts': 'ts', '.tsx': 'tsx' },
    minify: true,
    sourcemap: false,
    logLevel: 'warning',
    // VersionBadge / config 画面で表示用に
    //   __PLUGIN_VERSION__: build 番号 (manifest.json の整数)
    //   __PLUGIN_SEMVER__: semver (package.json の version)
    define: {
      __PLUGIN_VERSION__: JSON.stringify(String(pluginBuild)),
      __PLUGIN_SEMVER__: JSON.stringify(semver),
    },
  };

  await Promise.all([
    esbuild.build({
      ...commonOptions,
      entryPoints: ['src/desktop/index.tsx'],
      outfile: resolve(JS_OUT_DIR, 'desktop.js'),
    }),
    esbuild.build({
      ...commonOptions,
      entryPoints: ['src/config/index.tsx'],
      outfile: resolve(JS_OUT_DIR, 'config.js'),
    }),
  ]);
  console.log('[build] plugin/js/{desktop,config}.js generated');
}

// ----- 4-5. Tailwind CSS ビルド --------------------------------------------
function buildCss() {
  mkdirSync(CSS_OUT_DIR, { recursive: true });

  // desktop 用 CSS (グローバル + Tailwind)
  const desktopOut = resolve(CSS_OUT_DIR, 'desktop.css');
  const result = spawnSync(
    'tailwindcss',
    [
      '-i',
      'src/styles/global.css',
      '-o',
      desktopOut,
      '--minify',
    ],
    { stdio: 'inherit' },
  );
  if (result.status !== 0) {
    throw new Error(`tailwindcss build failed with exit ${result.status}`);
  }
  console.log('[build] plugin/css/desktop.css generated');

  // config 画面も同じスタイルを使う (小さいのでコピー)
  const contents = readFileSync(desktopOut, 'utf-8');
  writeFileSync(resolve(CSS_OUT_DIR, 'config.css'), contents);
  console.log('[build] plugin/css/config.css generated');
}

// ----- main ----------------------------------------------------------------
async function main() {
  const pluginBuild = bumpBuildNumber();
  const semver = (() => {
    try {
      const pkg = JSON.parse(readFileSync(resolve('package.json'), 'utf-8'));
      return typeof pkg.version === 'string' ? pkg.version : '0.0.0';
    } catch {
      return '0.0.0';
    }
  })();
  // Worker のバージョンは Plugin の build 番号 + ビルド時刻 (ISO8601 秒精度)
  const buildTime = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  const buildVersion = `plugin.${pluginBuild}+${buildTime}`;

  // tokens.css を再生成 (docs/design-handoff/customizer-wedge/tokens.json から)。
  // CSS bundle の前に走らせる必要がある (global.css が import するため)。
  buildTokens();

  // Worker バンドル → Plugin JS の順序依存はない (Worker の出力は Plugin の generated/ に
  // 書き出され、Plugin の bundleJs はそれを読みに行く) — ので bundleWorkerAsString が
  // 先に終わっていればよい。CSS は完全独立。
  await bundleWorkerAsString(buildVersion, buildTime);
  // Skill bundle は esbuild からの import 解決前に生成する必要がある (Plugin JS が
  // src/generated/skills-bundle.ts を読み込むため)。
  generateSkillsBundle();
  await Promise.all([bundleJs(pluginBuild, semver), Promise.resolve(buildCss())]);
  console.log(`[build] done (semver=${semver}, build=${pluginBuild})`);
}

main().catch((err) => {
  console.error('[build] failed:', err);
  process.exit(1);
});
