#!/usr/bin/env node
// build-tokens.mjs
//
// docs/design-handoff/customizer-wedge/tokens.json を読んで:
//   1. packages/plugin/src/styles/tokens.css に CSS 変数定義を出力 (light + dark)
//   2. 既存の global.css は import './tokens.css'; を 1 行入れるだけになる
//
// `pnpm plugin:build` の前段で自動実行される (build.mjs から呼ばれる)。
// 手動実行は `pnpm --filter @cowork-agent/plugin run tokens:build`。

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const TOKENS_JSON = resolve(REPO_ROOT, 'docs', 'design-handoff', 'customizer-wedge', 'tokens.json');
const OUT_CSS = resolve(__dirname, '..', 'src', 'styles', 'tokens.css');

function buildCssVariables(palette) {
  const lines = [];
  for (const [key, value] of Object.entries(palette)) {
    if (key.startsWith('$')) continue; // metadata
    lines.push(`  --cw-${key}: ${value};`);
  }
  return lines.join('\n');
}

function buildStatusVariables(palette, prefix) {
  const lines = [];
  for (const [key, value] of Object.entries(palette)) {
    if (key.startsWith('$')) continue;
    lines.push(`  --cw-${prefix}-${key}: ${value};`);
  }
  return lines.join('\n');
}

function main() {
  if (!existsSync(TOKENS_JSON)) {
    console.error(`❌ tokens.json が見つかりません: ${TOKENS_JSON}`);
    process.exit(1);
  }
  const tokens = JSON.parse(readFileSync(TOKENS_JSON, 'utf8'));

  const lightVars = buildCssVariables(tokens.color.light);
  const darkVars = buildCssVariables(tokens.color.dark);
  const statusVars = buildStatusVariables(tokens.color.status, 'status');
  const fileKindVars = buildStatusVariables(tokens.color['file-kind'], 'kind');

  // line-height / font-size の base はルートに反映 (個別 component は Tailwind class で上書き可)
  const baseFontSize = tokens.fontSize.base;
  const baseLineHeight = tokens.lineHeight.base;
  const fontSans = tokens.fontFamily.sans;
  const fontMono = tokens.fontFamily.mono;
  const fontImport = tokens.fontFamily['import-url'];

  const css = `/* AUTOGENERATED by scripts/build-tokens.mjs — DO NOT EDIT.
 * 編集する場合は docs/design-handoff/customizer-wedge/tokens.json を変更し、
 * \`pnpm --filter @cowork-agent/plugin run tokens:build\` を再実行する。
 *
 * Source: ${TOKENS_JSON.split('/').slice(-4).join('/')}
 * Version: ${tokens.$version ?? '?'}
 */

@import url('${fontImport}');

.cowork-agent-root {
  /* light theme (既定) — design-handoff の richColors(false, '#0d9488') と一致 */
${lightVars}

  /* status colors (WorkflowFooter / FileTree 等で個別 hex を使う系列) */
${statusVars}

  /* file kind バッジ色 (FileTree) */
${fileKindVars}

  /* font family */
  --cw-font-sans: ${fontSans};
  --cw-font-mono: ${fontMono};

  /* base typography */
  font-family: var(--cw-font-sans);
  font-size: ${baseFontSize};
  line-height: ${baseLineHeight};
}

.cowork-agent-root[data-theme='dark'] {
${darkVars}
}
`;

  mkdirSync(dirname(OUT_CSS), { recursive: true });
  writeFileSync(OUT_CSS, css, 'utf8');
  console.log(`[tokens] generated ${OUT_CSS.split('/').slice(-3).join('/')}`);
}

main();
